name: textz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.11.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.3
  image_field: ^0.0.10
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  introduction_screen: ^3.1.14
  flutter_otp_text_field: ^1.1.0+2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  flutter_contacts: ^1.1.8
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.2.1
  emoji_picker_flutter: ^2.2.0
  animated_splash_screen: ^1.3.0
  file_picker: 6.2.1
  photo_manager: ^3.1.1
  photo_view: ^0.15.0
  firebase_messaging: ^14.9.4
  socket_io_client: ^2.0.3+1
  agora_rtc_engine: ^6.3.2
  story_view: ^0.16.5
  awesome_notifications: ^0.9.3+1
  zego_uikit_signaling_plugin: ^2.7.14
  zego_uikit_prebuilt_call: ^4.12.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: SfUiText
    font:
      - asset: assets/fonts/SFUIText-Regular.ttf
        weight: 400