// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQnObejggu_6xCLmFEFDFwQcX4oiO8Fw',
    appId: '1:769856064245:web:711860d16bbe58cb0213bc',
    messagingSenderId: '769856064245',
    projectId: 'ios-whatsapp-clone-713d5',
    authDomain: 'ios-whatsapp-clone-713d5.firebaseapp.com',
    storageBucket: 'ios-whatsapp-clone-713d5.appspot.com',
    measurementId: 'G-YWL2N2R4KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp7d5Eq2Zlay5HEAcqd_Dj58bpPYMg_So',
    appId: '1:769856064245:android:bfb99db2bd4fac430213bc',
    messagingSenderId: '769856064245',
    projectId: 'ios-whatsapp-clone-713d5',
    storageBucket: 'ios-whatsapp-clone-713d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi8Ht0zD4DVZR3QLczFQOWvmE1Jg7yjw',
    appId: '1:769856064245:ios:32952721310cf1190213bc',
    messagingSenderId: '769856064245',
    projectId: 'ios-whatsapp-clone-713d5',
    storageBucket: 'ios-whatsapp-clone-713d5.appspot.com',
    iosBundleId: 'com.example.textz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi8Ht0zD4DVZR3QLczFQOWvmE1Jg7yjw',
    appId: '1:769856064245:ios:32952721310cf1190213bc',
    messagingSenderId: '769856064245',
    projectId: 'ios-whatsapp-clone-713d5',
    storageBucket: 'ios-whatsapp-clone-713d5.appspot.com',
    iosBundleId: 'com.example.textz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoQnObejggu_6xCLmFEFDFwQcX4oiO8Fw',
    appId: '1:769856064245:web:88e637651a64c9bf0213bc',
    messagingSenderId: '769856064245',
    projectId: 'ios-whatsapp-clone-713d5',
    authDomain: 'ios-whatsapp-clone-713d5.firebaseapp.com',
    storageBucket: 'ios-whatsapp-clone-713d5.appspot.com',
    measurementId: 'G-178CDT9MNW',
  );
}
